---
title: "Sparse no-U-turn sampling for TMB and RTMB models"
author: "Cole C. Monnahan"
date: "`r Sys.Date()`"
bibliography: refs.bib
output:
  rmarkdown::html_vignette:
  toc: true
vignette: >
  %\VignetteIndexEntry{Sparse no-U-turn sampling for TMB and RTMB models}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

## Summary

`SparseNUTS` provides an interface for performing Bayesian
analyses using the no-U-turn (NUTS) MCMC algorithm [@hoffman2014] for
TMB [@kristensen2016] and RTMB models. It is closely related to
the `adnuts` package which provides functionality for ADMB
[@fournier2012] models.

For TMB models the NUTS algorithm is in the Stan software
[@carpenter2017] and linked through the
[StanEstimators](https://github.com/andrjohns/StanEstimators) R
package. `SparseNUTS` implements the sparse NUTS (SNUTS) algorithm of
[@monnahan2025] by decorrelating and descaling the posterior
distribution prior to passing to Stan. For models with high
correlations and sparse precision matrices, SNUTS can
substantially improve sampling efficiency.  Importantly, it works
smiliarly for TMB and RTMB models, and can be run on models from
existing packages built on either of these platforms (e.g., `glmmTMB`).

This package was originally developed inside of the `adnuts`
package but was split off in late 2025 to have a separate package
for TMB and ADMB models.  The `tmbstan` package also provides an
interface to the Stan software, but lacks the ability to
decorrelate the target distribution prior to sampling.
`SparseNUTS` provides more flexible options related to the mass
matrix.

Basic usage for a TMB or RTMB object `obj` is shown as
follows, with a more in depth article on the website.
````{r, eval=FALSE}
fit <- sample_snuts(obj)
print(fit)
plot(fit)
pairs(fit, order='slow')
post <- as.data.frame(fit)
launch_shinytmb(fit)
````



## References
