test_that("diagnostics and plotting", {
  skip_if(skip_TMB)
  fit <- readRDS('fit.RDS')
  sp <- extract_sampler_params(fit)
  expect_is(sp,  'data.frame')
  plot_sampler_params(fit, plot=TRUE)
  sp <- plot_sampler_params(fit, plot=FALSE)
  expect_equal('ggplot2::ggplot', class(sp)[1])
  pairs(fit)
  pairs(fit, pars=1:3, order='slow')
  pairs(fit, pars=1:3, order='fast')
  pairs(fit, pars=c('x1', 'lp__', 'x2'), add.monitor=FALSE)
  expect_warning(pairs(fit, pars=c('x1', 'x0', 'x3')), 'Some par names did not match')
  expect_error(pairs(fit, pars=c('x1')), 'only makes sense for >=2')
  pairs(fit, add.mle=FALSE)
  pairs(fit, add.mle=FALSE, diag='hist')
  pairs(fit, add.mle=FALSE, diag='acf')
  pairs(fit, inc_warmup=TRUE)
  pairs(fit, inc_warmup=TRUE, add.inits=TRUE)
  pairs(fit, inc_warmup=FALSE, add.inits=TRUE)
  expect_error(pairs(fit, add.mle=FALSE, diag='bad'), 'should be one of')
  plot_marginals(fit)
  plot_marginals(fit, add.monitor=FALSE)
  plot_marginals(fit, add.mle=FALSE)
  plot_uncertainties(fit)
  plot_uncertainties(fit, log = FALSE)
  x <- plot_uncertainties(fit, plot=FALSE)
  expect_is(x, 'data.frame')
})
