test_that("diagnostics and plotting", {
  skip_if(skip_TMB)
  fit <- readRDS('fit_snuts.RDS')
  sp <- extract_sampler_params(fit)
  expect_is(sp,  'data.frame')
  plot_sampler_params(fit, TRUE)
  pairs(fit)
  pairs(fit, pars=1:3, order='slow')
  pairs(fit, pars=1:3, order='fast')
  pairs(fit, pars=c('x1', 'lp__', 'x2'), add.monitor=FALSE)
  expect_warning(pairs(fit, pars=c('x1', 'x0', 'x3')), 'Some par names did not match')
  expect_error(pairs(fit, pars=c('x1')), 'only makes sense for >=2')
  pairs(fit, add.mle=FALSE)
  pairs(fit, add.mle=FALSE, diag='hist')
  pairs(fit, add.mle=FALSE, diag='acf')
  expect_error(pairs(fit, add.mle=FALSE, diag='bad'), 'should be one of')
  plot_marginals(fit)
  plot_marginals(fit, add.monitor=FALSE)
  plot_marginals(fit, add.mle=FALSE)
  x <- plot_uncertainties(fit, plot=FALSE)
})
